---
- name: install git
  apt:  pkg=git state=present update_cache=yes

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=present update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
    - Start Nginx
